services:
  share-checker:
    image: share-checker:latest
    restart: always
    depends_on:
      - nfs-server # Optional: Only needed if the nfs server is supposed to be running locally
    environment:
      - NFS1=server:/mnt/share # Replace with the correct server and share path
        # Add more shares here in the format NFS[0-9]:/path/to/share
      - TIMEOUT=60 # Optional: Default 60s
      - DEBUG=true # Optional: Only for debugging
    networks:
      - app-network
  app:
    image: hello-world
    restart: always
    depends_on:
      nfs-checker:
        condition: service_healthy
    volumes:
      - /mnt/nfs1:/mnt/nfs1:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
