name: CI and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build share-checker image
        run: |
          docker build --pull -t share-checker:latest ./share-checker

      - name: Start share-checker container
        run: |
          docker run -d \
            --name share-checker \
            --health-cmd="test -f /tmp/shares-ready" \
            --health-interval=10s \
            --health-timeout=5s \
            --health-retries=3 \
            --health-start-period=10s \
            -e NFS1=server:/export/test \
            -e TIMEOUT=60 \
            share-checker:latest

      - name: Mock NFS ready file
        run: |
          docker exec share-checker touch /tmp/shares-ready

      - name: Wait for container to become healthy
        run: |
          timeout 60s bash -c "until docker inspect -f '{{.State.Health.Status}}' share-checker | grep -q healthy; do sleep 5; done"

      - name: Run app container
        run: |
          docker run --rm --name app hello-world || echo "hello-world ran"

      - name: Cleanup
        if: always()
        run: |
          docker rm -f share-checker || true

  publish:
    name: Push Docker image
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/share-checker:latest
          docker build -t $IMAGE_NAME ./share-checker
          docker push $IMAGE_NAME
